version: 2
executorType: docker

containerInfo:
  - image: python:2.7

stages:
  build:
    workDir: ~/kaku
    steps:
      - type: checkout
      - type: shell
        name: Install Environment
        command:  pip install -U pip wheel
      - type: shell
        name: Install pyenv
        command: |
          curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
          echo 'export PATH="/root/.pyenv/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
          echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bash_profile
      - type: shell
        name: Install Dependencies
        command: make dev
      - type: shell
        name: Test
        command: make ci