version: 2
executorType: docker

containerInfo:
  - image: python:2.7

stages:
  build:
    workDir: ~/kaku
    steps:
      - type: checkout
      - type: shell
        name: Install Environment
        command:  pip -U install pip, wheel
      - type: shell
        name: Install Dependencies
        command: make dev
      - type: shell
        name: Test
        command: make ci